### ISSUE TITLE
[programação] (35 mangos) Pausa durante jogo + botão "Voltar" para Menu

### ISSUE THREAD

**Issue by fegemo** [fegemo/cefet-games-brushmyteethplz#51]
O grupo deve implementar a pausa durante a sequência de minigames. A pausa foi implementada, mas funciona apenas ENTRE um MiniGame e outro. Atenção especial para quando o a tela de jogo (PlayingGameScreen) estiver nos estados de transição e com o cronômetro de fim dos últimos 3s ativado.

O botão "Menu" ou "Voltar" deve aparecer assim que o jogo for pausado e, ao ser ativado, ele deve mostrar uma confirmação.

Valor: **35 mangos**

**Comment by dangon1** [comment]
Como eu ativo o pause da forma que ele está funcionando hoje? Tentei apertar vários botões e nenhum ativou ele. E em qual classe ele está implementado?

**Comment by dangon1** [comment]
Pensei em criar um botão de pause na HUD que chama um pop up para mostrar o botão "Menu". Mas preciso saber como o pause anterior está implementado
